import type { ReportHistoryEntry } from "../api/reportHistory";
import { toCsv } from "./csv";
import { describe } from "./reportHistoryText";

const SECTION_LABEL: Record<string, string> = { online: "Online", offline: "Offline", all: "Full" };

const HEADERS = ["Report", "Covers", "Detail", "Category / source", "Section", "Generated at", "Generated by"];

/// A Report History list (Daily, Variance or Audit) as CSV text, in the order
/// given. Text cells starting with = + - @ are prefixed with an apostrophe so
/// a stored value can't run as a spreadsheet formula.
export function reportHistoryCsv(entries: ReportHistoryEntry[]): string {
  const safe = (v: string) => (/^[=+\-@]/.test(v) ? `'${v}` : v);
  return toCsv(
    HEADERS,
    entries.map((e) => {
      const { title, detail, category } = describe(e);
      return [
        e.type,
        safe(title),
        safe(detail),
        safe(category),
        e.section ? (SECTION_LABEL[e.section] ?? e.section) : "",
        e.generatedAt,
        safe(e.generatedBy?.name ?? ""),
      ];
    }),
  );
}
