import { describe, expect, it } from "vitest";
import type { ReportHistoryEntry } from "../api/reportHistory";
import { reportHistoryCsv } from "./reportHistoryCsv";

const entry = (over: Partial<ReportHistoryEntry> = {}): ReportHistoryEntry => ({
  id: 1,
  type: "Daily Report",
  scope: "2026-10-09",
  route: "/daily-report?history=1&date=2026-10-09",
  generatedAt: "2026-10-09T08:00:00.000Z",
  generatedBy: { id: 1, name: "Ana Cruz", username: "ana" },
  section: "online",
  ...over,
});

describe("reportHistoryCsv", () => {
  it("writes one readable line per report", () => {
    const [header, line] = reportHistoryCsv([entry()]).split("\r\n");
    expect(header).toBe("Report,Covers,Detail,Category / source,Section,Generated at,Generated by");
    expect(line.startsWith("Daily Report,")).toBe(true);
    expect(line.endsWith(",1 day,,Online,2026-10-09T08:00:00.000Z,Ana Cruz")).toBe(true);
  });

  it("reads the shift and source of an Audit report from its route", () => {
    const line = reportHistoryCsv([
      entry({ type: "Audit Report", route: "/manual-count?history=1&date=2026-10-09&shift=NIGHT&source=OFFLINE", section: "offline" }),
    ]).split("\r\n")[1];
    expect(line).toContain("Night shift");
    expect(line).toContain("Offline");
  });

  it("leaves the section blank for entries from before it was recorded, and tolerates no user", () => {
    const line = reportHistoryCsv([entry({ section: null, generatedBy: null })]).split("\r\n")[1];
    expect(line.endsWith("1 day,,,2026-10-09T08:00:00.000Z,")).toBe(true);
  });

  it("is only the header for an empty list", () => {
    expect(reportHistoryCsv([])).toBe("Report,Covers,Detail,Category / source,Section,Generated at,Generated by");
  });
});
